"""Self-contained, printable five-slide presentation, generated from verified calculations."""
from html import escape

def presentation(data, plan, result, title, version):
    e = lambda value: escape(str(value), quote=True)
    n = lambda value: f'{value:,.2f}'.replace(',', ' ').replace('.', ',')
    money = lambda value: f'{value:,}'.replace(',', ' ') + ' ₸'
    measures = {m['id']: m for m in data['measures']}
    districts = {d['id']: d for d in data['districts']}
    rows = ''.join(f'<tr><td>{i+1}</td><td>{e(measures[p["measure_id"]]["name"])}</td><td>{e(districts[p["district_id"]]["name"] if p.get("district_id") else "Весь город")}</td><td>{money(measures[p["measure_id"]]["cost_tenge"])}</td></tr>' for i,p in enumerate(plan))
    changes = ''.join(f'<tr><td>{e(d["name"])}</td><td>{n(d["before"])}</td><td>{n(d["after"])}</td><td>{n(d["delta"])}</td></tr>' for d in result['changes'])
    strengths = ''.join('<li>'+e(s)+'</li>' for s in result['explanation']['strengths'])
    risks = ''.join('<li>'+e(s)+'</li>' for s in result['explanation']['risks'])
    p = result['prediction']; event = result['event']
    slides = [
        f'<p class="eyebrow">ASTANA CITY LAB · 01 / 05</p><h1>{e(title)}</h1><p class="lead">Пять решений для качества городской жизни</p><div class="hero">{n(result["fact"]["score"])} <span>→</span> {n(p["score"])}</div><p>Astana Quality of Life Score · изменение {n(result["delta"])} балла</p><p class="note">Данные v{version} · {e(event["name"])} · горизонт 8 кварталов</p>',
        f'<p class="eyebrow">02 / 05 · РЕСУРСЫ</p><h1>Бюджет и условия</h1><div class="metrics"><div><small>Общий бюджет</small><strong>{money(event["original_budget_tenge"])}</strong></div><div><small>Резерв на событие</small><strong>{money(event["reserve_tenge"])}</strong></div><div><small>Стоимость инициатив</small><strong>{money(p["cost_tenge"])}</strong></div><div><small>Свободный остаток</small><strong>{money(p["remaining_tenge"])}</strong></div></div><p>{e(event["description"])}</p><p class="note">Ровно 5 разных мер, не более 2 из одного направления. Резерв не является шестым решением: это внешнее условие стресс-теста.</p>',
        f'<p class="eyebrow">03 / 05 · РЕШЕНИЯ</p><h1>Инвестиционный план</h1><table><tr><th>№</th><th>Мера</th><th>Территория</th><th>Стоимость</th></tr>{rows}</table>',
        f'<p class="eyebrow">04 / 05 · РЕЗУЛЬТАТ</p><h1>Факт и прогноз</h1><table><tr><th>Район</th><th>Факт</th><th>Прогноз</th><th>Изменение</th></tr>{changes}</table><p>Критических показателей: {len(result["fact"]["critical"])} → {len(p["critical"])}. Вклад решений относительно условий сценария: {n(result["decision_delta"])} балла.</p><p class="note">Score = 70% среднего по населению + 30% слабейшего района − число показателей ниже 40.</p>',
        f'<p class="eyebrow">05 / 05 · ВЫВОДЫ</p><h1>Эффекты и компромиссы</h1><div class="columns"><div><h2>Сильные стороны</h2><ul>{strengths}</ul></div><div><h2>Риски</h2><ul>{risks}</ul></div></div><p class="note">Синтетические данные хакатона. Прогноз вычислен Python-моделью; это не официальная статистика, не реальные сметы и не подтверждённый прогноз Астаны.</p>',
    ]
    return '<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>body{margin:0;background:#e9eff4;color:#173249;font:20px/1.5 "Segoe UI",Arial,sans-serif}nav{position:sticky;top:0;padding:12px 4%;background:#173249;color:white;font-size:14px;z-index:2}button{padding:8px 15px;border:0;border-radius:6px;cursor:pointer;margin-right:8px}section{box-sizing:border-box;max-width:1200px;min-height:675px;margin:28px auto;padding:65px;background:white;border-radius:12px;box-shadow:0 8px 30px #17324912}h1{font-size:46px;line-height:1.2;overflow-wrap:anywhere}h2{font-size:24px}.eyebrow{color:#087d70;letter-spacing:.12em;font-size:15px;font-weight:700}.hero{font-size:90px;font-weight:750;color:#087d70}.hero span{color:#9ab0bd}.lead{font-size:28px}.note{font-size:15px;color:#60788a}.metrics,.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}.metrics div{padding:20px;background:#edf6f3}.metrics strong{display:block;font-size:27px}table{width:100%;border-collapse:collapse;font-size:18px}td,th{text-align:left;border-bottom:1px solid #dce6ed;padding:14px 8px}li{margin-bottom:10px}footer{font-size:12px;color:#60788a;text-align:center;padding:16px}@media(max-width:700px){section{padding:25px;margin:12px;min-height:0}h1{font-size:32px}.hero{font-size:54px}.metrics,.columns{grid-template-columns:1fr}table{font-size:13px}td,th{padding:8px 3px}}@media print{@page{size:A4 landscape;margin:10mm}body{background:white;font-size:14px}nav,footer{display:none}section{page-break-after:always;break-after:page;min-height:0;margin:0;padding:15px;box-shadow:none;border-radius:0}section:last-of-type{break-after:auto}h1{font-size:32px;margin:12px 0}.hero{font-size:64px}.metrics strong{font-size:22px}table{font-size:14px}.note{font-size:12px}li{margin-bottom:6px}}</style><nav><button onclick="window.print()">Печать / сохранить PDF</button>Презентация сценария · 5 слайдов · прокрутите вниз</nav>'+''.join('<section>'+s+'</section>' for s in slides)+'<footer>Аким на 5 часов · автономная презентация, работает без сервера и API-ключей</footer></html>'
